[package]
name = "gpurepr"
authors = ["Peter Jin <peterhaijin@gmail.com>"]
version = "0.0.0"
edition = "2018"

[lib]
name = "gpurepr"
path = "src/lib.rs"

[dependencies]
cudart = { git = "https://github.com/peterhj/cudart", features = ["cuda_10_0"] }
